### ISSUE TITLE
make docker file for node

### ISSUE THREAD

**Issue by stresskiller** [creativechain/crea#1]
it would be nice to have a docker file for the witness node so it could run on a synology nas , many people have a nas doing absolutely nothing most of the time, if you could make a "light " version of the node , and host the images on an amazon server lik they do on Steemit.com for example,  or just let the lighter nodes only handle the friends / followers data to help the main content nodes light nodes would get less rewards but it does make the overal net work more stable in the end .

**Comment by creativechain-git** [comment]
Are you looking for this? https://cloud.docker.com/u/creary/repository/docker/creary/crea

**Comment by stresskiller** [comment]
that might be a start will try it out in the morning , almost midnight now here :)

**Comment by stresskiller** [comment]
it seems to run on my ds918+ Nas , now i only need to find what ports i need to forward no info on docker page about that :)

**Comment by ander7agar** [comment]
Seems nothing to do here.
